### ISSUE TITLE
Required CMake Version

### ISSUE THREAD

**Issue by MartinK84** [spinicist/riesling#21]
When trying to compile from scratch on Ubuntu 18.04 LTS after a git clone I'm greeted with 
"CMake 3.16 or higher is required.  You are running version 3.10.2"

Is such a high version of CMake really required?
It's also kind of confusing as the documentation for running the pre-compiled binaries states that Ubuntu 16.04 is required.
If such a recent CMake version is required then this should also be stated in the documentation.

**Comment by spinicist** [comment]
Hello,

After some experimenting I think riesling can be built with CMake 3.10.2 if I do two things:
1 - Drop the C++ standard from 20 to 17. It turns out riesling is not using any C++20 features yet (I am in a different project).
2 - Edit https://github.com/spinicist/riesling/blob/main/CMakeLists.txt#L24 to use the older `add_definitions()` command which has been superseded by `add_compile_definitions()` as of 3.12.

The pre-compiled binaries are compiled using the Github Actions infrastructure. The list of software installed on the 16.04 runner is [here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1604-README.md), this includes CMake 3.20. I actually need to update the Github Action because the 16.04 runner is deprecated. I think the base version of CMake in 18.04 is still CMake 3.10, but the Github runner will also have 3.20 installed.

Given that the required edits to allow compiling with 3.10 are minimal I think the best course of action is to make them. Do you agree?

**Comment by MartinK84** [comment]
If it doesn't break anything and stays compatible with a newer version of CMake and if you are not planning on using any C++20 features in the near future I would suggest making the edits. 

The reason why I opened this ticket is that you should keep in mind how probably many users might be using riesling. Because of the memory and computation power requirements of 3D non-cartesian reconstructions, many people will probably try to compile and run riesling on a remote computation server where the average user often can't just easily install software and update for example CMake.

This also brings up another question, is riesling by default compiled in static mode (so that I could compile on a desktop computer and copy the binary with all statically linked libraries to a computation server)? If this is not the default - is there a flag for the compilation process to make it compile as static? BART for example has this option and it's extremely important for our IT infrastructure because the desktop clients and servers are all running different Ubuntu versions (ranging from 12.04 to 20.04)

**Comment by spinicist** [comment]
I have updated the CMakeLists.txt file.

Yes, riesling is compiled with static linking, including a statically linked `libgcc` and `libstdc++`. This is taken care of in the CMake [toolchain](https://github.com/spinicist/cmake/blob/2621fa8e2f6bd8f7fc07a6b604b30c3a8180808c/x64-linux-avx2.cmake) and mentioned in the README (under installation). As I understand it, provided the CPU supports AVX2, the pre-compiled binaries should run on any Linux with the same or higher version of `glibc`. Hence the desire to build on as old a version of Ubuntu as is available in the CI.

**Comment by MartinK84** [comment]
Okay good to hear that it's always static, then I will try to build on my desktop Ubuntu and deploy to various servers later :-) 

With the fixed CMakeLists.txt it did process further and is now stuck during the actual `cmake --build build` call with an `Error: could not load cache` (before that I had to manually `mkdir build`). I would assume that it's trying to load the CMake cache from the build directory where the files aren't present. If I run `cmake --build ./` then it at least starts to compile but dies with an `src/main_grid.cpp:9:10: fatal error: filesystem: No such file or directory` from `#include <filesystem>`. The latter is probably due to Ubuntu 18.04 only having glibc 2.27? The former error with cmake might be related to the older CMake version?

If I'm not mistaking (please correct me if I'm wrong) this would mean that you would need Ubuntu 20.04 for compilation as it's the only Ubuntu with glibc > 2.30. This then probably will also have a recent enough CMake version.

One more thing for the build process, compilation requires the `ninja-build` ubuntu package to be installed, would probably be a good idea to add this to the dependencies in the README; then I think you can close this issue

Sorry for the mess :-)

**Comment by MartinK84** [comment]
Quick update, I tried to clone and build on Ubuntu 20.04 on my laptop and everything worked out fine there. So maybe add to the README that compilation from source requires a recent Ubuntu.

**Comment by spinicist** [comment]
Splitting your issues into a list:
1. I'm surprised you had to `mkdir build`, I've not had to do that. I am wondering if this is something that changed in CMake after version 3.10? Regardless, I have added a `mkdir -p build` to `bootstrap.sh`.
2. The complaint about `filesystem` missing implies that the system compiler is not C++17 compliant (which is unsurprising for an old Ubuntu). The Github CI has GCC 9 available which I use. I think GCC 8 will also work, but not GCC 7 which appears to be missing `std::filesystem` although otherwise looks C++17 complete. I have noted the required compilers in the README, they should have been there already.
3. Apologies, I use Ninja so much I forget it's not available everywhere. I have added a check to `bootstrap.sh` for Ninja, if it is not available then the default CMake generator will be used.
4. With regards to `glibc` I think I may have misunderstood the minimum version required. Here is the output of `ldd -v` on the Github compiled version.

```
login2 ➜  Downloads  ldd -v ./riesling
	linux-vdso.so.1 =>  (0x00007fff33174000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f985f4a9000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007f985f1a7000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f985efa3000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007f985ebd5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f985f6c5000)

	Version information:
	./riesling:
		libdl.so.2 (GLIBC_2.2.5) => /usr/lib64/libdl.so.2
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		libpthread.so.0 (GLIBC_2.3.2) => /usr/lib64/libpthread.so.0
		libpthread.so.0 (GLIBC_2.2.5) => /usr/lib64/libpthread.so.0
		libc.so.6 (GLIBC_2.15) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.8) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.3) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.7) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib64/libc.so.6
		libm.so.6 (GLIBC_2.2.5) => /usr/lib64/libm.so.6
	/usr/lib64/libpthread.so.0:
		ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.14) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib64/libc.so.6
	/usr/lib64/libm.so.6:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.2.5) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /usr/lib64/libc.so.6
	/usr/lib64/libdl.so.2:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_PRIVATE) => /usr/lib64/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib64/libc.so.6
	/usr/lib64/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
```

I think the highest version reported is the minimum required, which if I understand this output correctly is actually 2.17?

**Comment by MartinK84** [comment]
1. The next problem seems to be a lovely `Error: could not load cache` because I think it's looking for the CMake cache within the build directory and this directory is empty. I think this is simply a problem with the different CMake versions. I'm able to initiate a build by running `cmake --build .` instead of `cmake --build build`
2.  (and 4.) That's a good catch so it's probably related not to the glibc version being too low but the gcc-7 I'm using. I did install gcc-8.4.0 and the compilation did start and continue for a couple of files but then died with probably another incompatibility:

```
[27/63] Building CXX object CMakeFiles/vineyard.dir/src/gridder.cpp.o
FAILED: CMakeFiles/vineyard.dir/src/gridder.cpp.o
/usr/bin/c++  -DEIGEN_USE_THREADS -DFMT_LOCALE -DITK_IO_FACTORY_REGISTER_MANAGER -DSCN_HEADER_ONLY=0 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -IITKFactoryRegistration -isystem vcpkg_installed/x64-linux/include/ITK-5.1 -isystem vcpkg_installed/x64-linux/share/eigen3/../../include/eigen3 -isystem vcpkg_installed/x64-linux/include -O3 -DNDEBUG   -std=c++1z -MD -MT CMakeFiles/vineyard.dir/src/gridder.cpp.o -MF CMakeFiles/vineyard.dir/src/gridder.cpp.o.d -o CMakeFiles/vineyard.dir/src/gridder.cpp.o -c src/gridder.cpp
src/gridder.cpp: In constructor ‘Gridder::Gridder(const Trajectory&, float, Kernel*, bool, Log&)’:
src/gridder.cpp:41:45: error: ambiguous overload for ‘operator=’ (operand types are ‘Sz3’ {aka ‘Eigen::DSizes<long int, 3>’} and ‘<brace-enclosed initializer list>’)
     dims_ = {gridSz, gridSz, info_.matrix[2]};
                                             ^
In file included from vcpkg_installed/x64-linux/share/eigen3/../../include/eigen3/unsupported/Eigen/CXX11/Tensor:91,
                 from src/types.h:8,
                 from src/kernel.h:3,
                 from src/kernel_kb.h:3,
                 from src/kernels.h:3,
                 from src/gridder.h:3,
                 from src/gridder.cpp:1:
vcpkg_installed/x64-linux/share/eigen3/../../include/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorDimensions.h:372:29: note: candidate: ‘Eigen::DSizes<DenseIndex, NumDims>& Eigen::DSizes<DenseIndex, NumDims>::operator=(Eigen::array<DenseIndex, NumDims>&) [with DenseIndex = long int; int NumDims = 3; Eigen::array<DenseIndex, NumDims> = std::array<long int, 3>]’
   EIGEN_DEVICE_FUNC DSizes& operator = (const array<DenseIndex, NumDims>& other) 
```

I will see if I can find a PPA for gcc-9 for my office Ubuntu 18.04 and see if this resolves this issue.

**Comment by spinicist** [comment]
1. I've added an explicit `cd build` command to the bootstrap script which I hope you should stop this.
2. I've added an explicit type to the right-hand side of that assignment. I don't have GCC 8.4 easily available to check, but that should fix it. However there may be other such instances.

**Comment by MartinK84** [comment]
1. Still fails with the same error unless I run `cmake --build .` myself
2. I have now installed gcc 9.4.0 and am happy to say that I was finally able to compile riesling and that it also runs :-)

**Comment by MartinK84** [comment]
I have now tried to actually use riesling across our Linux based server infrastructure - unfortunately without much success. Just for comparison I did also try now the pre-compiled binary and the results are as follows:

System | Self-compiled | Pre-compiled
--- | --- | ---
Ubuntu 14.04.3 LTS | 💔 GLIBC ad CXXABI version missmatch | 💔 Ilegal instructions
Ubuntu 16.04.6 LTS | 💔 GLIBC ad CXXABI version missmatch | 💔 Ilegal instructions
Ubuntu 18.04.5 LTS | 💔 GLIBC version missmatch | :green_heart: 
Ubuntu 18.04.5 LTS  <br> (desktop computer used to compile)| :green_heart: | 💔 Ilegal instructions
CentOS Stream 8 | 💔 GLIBC version missmatch | :green_heart: 

Just as a comparison, a static compiled BART version runs on all of those systems. Is there anything one could do to increase the compatbility of the compiled riesling binary, possibly also static link glibc, etc.?

**Comment by spinicist** [comment]
I think the illegal instructions are due to a lack of AVX2 support in the CPUs in those machines. I thought AVX2 was pretty widespread, but my expectations are clearly a bit ahead of the times. I have changed the CI Linux build to not use AVX2, once the tests pass I will tag a new version to build a new pre-compiled version.

Are you building BART on the same machine you built riesling? If yes then I am surprised by the GLIBC missmatches and will have to do some reading.

**Comment by MartinK84** [comment]
Yepp, BART is being compiled on the same computer. It's basically my Desktop computer where I have local root and can easily install dependencies and libraries. For BART all I did was change the `SLINK?`=1 in the Makefile. It could also be that BART is more forgiving because it's in general just plain C trying to use as few libraries as possible.

**Comment by spinicist** [comment]
v0.5 has finished building as is available on the Github releases page. If you can check if it runs on your available machines I'd be very grateful - I suspect 14.04 will fail, but I hope 16.04 and up will work.

**Comment by MartinK84** [comment]
Looking much better :)

System | Pre-compiled 0.5
--- | --- 
Ubuntu 14.04.5 LTS | :green_heart: 
Ubuntu 16.04.5 LTS | :green_heart: 
Ubuntu 18.04.5 LTS | :green_heart:

**Comment by spinicist** [comment]
Oh fantastic! That is good news it works all the way back to 14.04.

**Comment by MartinK84** [comment]
Continuing on the Make problems I'm trying the latest changes and ran into two problems again.

First, vcpkg.cmake is now complaining about the non-recognized sub-command PREPEND, which I think was only introduced later than the cmake 3.10.2 I'm using. It's strange however that this did not happen before and has thus to do with c0f7ce4f926a8d2364ca17bc50d5e76d2d15804b

Secondly, I'm now trying to build without Ninja and the bootstrap.sh fails with `./bootstrap.sh: line 23: GEN: unbound variable`. I guess there is an else missing that sets the CMake to Unix Makefiles explicitly?

**Comment by spinicist** [comment]
The second point is indeed a missing `else`. I have added it. Sorry about that.

After a bit of digging on the first point I concur that commit is problematic. I updated vcpkg and it looks like a commit from about a month ago on their master branch introduced `PREPEND` into `vcpkg.cmake`, which is only supported by 3.15 and higher.

On the `cmake` branch I think I've done the correct `git` commands to roll back `vcpkg` to just before that commit. Please could try checking out the `cmake` branch and see if it works with 3.10?

**Comment by MartinK84** [comment]
Both things work now, the cmake branch compiles without any errors using normal Unix Make instead of Ninja and the VCPKG errors are also gone. The compatibility of the compiles binary did also slightly improve. If I compile at  Ubunut 18.04 I can also finally run it on all of our other Ubuntu 18.04 systems :-)

**Comment by spinicist** [comment]
Great! I'm closing this issue, please re-open if I missed something.
